# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY . .
RUN npm ci --ignore-scripts
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/bin ./bin
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

ENV CONTENTSTACK_API_KEY=stack_api_key
ENV CONTENTSTACK_MANAGEMENT_TOKEN=stack_management_token

ENTRYPOINT ["node", "bin/mcp-server.js"]
